import Head from 'next/head'
import { Mochiy_Pop_One } from 'next/font/google'
import * as S from "../styles/Index_style.js"
import {useEffect, useState } from 'react'


const Mochiy = Mochiy_Pop_One({
  subsets: ['latin'],
  weight: ['400'],

})

// let corX = ""
// let corO = ""

export default function Home() {
  const [playerTurn, setPlayerTurn] = useState("X")
  const [colorX,setColorX] = useState("")
  const [colorO,setColorO] = useState("")

  return (
    <>
      <S.GlobalStyle />
      <Head>
        <title>JOGO DA VÉIA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <S.MainBox $win={OWin || XWin}>

        <S.MainFirstBox>

          <S.PlayerTitle className={Mochiy.className}>Player: <S.PlayerSimbol $iscoloro={colorO} $iscolorx={colorX} value={playerTurn}>{playerTurn}</S.PlayerSimbol></S.PlayerTitle>
          <S.ChangeColor className={Mochiy.className}
            onClick={() => {
             setColorO(colorO === "" ? "blue":"")
             setColorX(colorX === ""? "#c1121f":"")
            }}
          >Mudar Cor</S.ChangeColor>

        </S.MainFirstBox>

        <S.GameBox>

          <S.LineSquare>

            <S.Square $isborderright="0.75vw solid" $isborderbottom="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX} buttonId={1}  />
            </S.Square>

            <S.Square $isborderbottom="0.75vw solid" $isborderright="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={2}  />
            </S.Square>

            <S.Square $isborderbottom="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn}  colorO={colorO} colorX={colorX} buttonId={3}  />
            </S.Square>

          </S.LineSquare>

          <S.LineSquare>

            <S.Square $isborderbottom="0.75vw solid" $isborderright="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={4} />
            </S.Square>

            <S.Square $isborderbottom="0.75vw solid" $isborderright="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={5}/>
            </S.Square>

            <S.Square $isborderbottom="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={6}/>
            </S.Square>

          </S.LineSquare>

          <S.LineSquare>

            <S.Square $isborderright="0.75vw solid">
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={7}/>
            </S.Square>

            <S.Square $isborderright="0.75vw solid">
              <Moves  setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={8}/>
            </S.Square>

            <S.Square>
              <Moves setPlayerTurn={setPlayerTurn} colorO={colorO} colorX={colorX}  buttonId={9}/>
            </S.Square>

          </S.LineSquare>


        </S.GameBox>
        {(XWin || OWin) && <S.ButtonReload onClick={() => {location.reload()}} className={Mochiy.className}>
          Jogar Novamente
        </S.ButtonReload>}
      </S.MainBox>
    </>
  )
}

let countMoves = 0
let lastMove = ""
let X1 = ""
let X2 = ""
let X3 = ""
let X4 = ""
let X5 = ""
let X6 = ""
let X7 = ""
let X8 = "" 
let X9 = ""

let O1 = ""
let O2 = ""
let O3 = ""
let O4 = ""
let O5 = ""
let O6 = ""
let O7 = ""
let O8 = "" 
let O9 = ""

let XWin
let OWin
let aviso = ""

function Moves({ setPlayerTurn, colorO, colorX, buttonId }) {
  const [player, setPlayer] = useState("")

  const HandlePlayer = () => {
    if (lastMove === "") {
      setPlayer("X")
      lastMove = "X"
      setPlayerTurn("O")
      countMoves++
    } else if (lastMove === "X") {
      setPlayer("O")
      lastMove = "O"
      setPlayerTurn("X")
      countMoves++
    } else if (lastMove === "O") {
      setPlayer("X")
      lastMove = "X"
      setPlayerTurn("O")
      countMoves++
    }
  }

  const FuncaoTeste = (item) =>{

    if(OWin == true && aviso === ""){
      alert("Parabéns ao Jogador(a) O!!! Clique abaixo para jogar novamente!!!")
      aviso = true
    } else if(item.target.value === "X" && item.target.id === "1"){
      X1 = true
      console.log("foi X1")
    } else if(item.target.value === "X" && item.target.id === "2"){
      X2 = true
      console.log("foi X2")
    } else if(item.target.value === "X" && item.target.id === "3"){
      X3 = true
      console.log("foi X3")
    } else if(item.target.value === "X" && item.target.id === "4"){
      X4 = true
      console.log("foi X4")
    } else if(item.target.value === "X" && item.target.id === "5"){
      X5 = true
      console.log("foi X5")
    } else if(item.target.value === "X" && item.target.id === "6"){
      X6 = true
      console.log("foi X6")
    } else if(item.target.value === "X" && item.target.id === "7"){
      X7 = true
      console.log("foi X7")
    } else if(item.target.value === "X" && item.target.id === "8"){
      X8 = true
      console.log("foi X8")
    } else if(item.target.value === "X" && item.target.id === "9"){
      X9 = true
      console.log("foi X9")
    }

    if(XWin == true && aviso == ""){
      alert("Parabéns ao Jogador(a) X!!! Clique mais uma vez para jogar novamente!!!")
      aviso = true
    } else if(item.target.value === "O" && item.target.id === "1"){      
      O1 = true
      console.log("foi O1")
    }else if(item.target.value === "O" && item.target.id === "2"){
      O2 = true
      console.log("foi 02")
    } else if(item.target.value === "O" && item.target.id === "3"){
      O3 = true
      console.log("foi 03")
    } else if(item.target.value === "O" && item.target.id === "4"){
      O4 = true
      console.log("foi 04")
    } else if(item.target.value === "O" && item.target.id === "5"){
      O5 = true
      console.log("foi 05")
    } else if(item.target.value === "O" && item.target.id === "6"){
      O6 = true
      console.log("foi 06")
    } else if(item.target.value === "O" && item.target.id === "7"){
      O7 = true
      console.log("foi 07")
    } else if(item.target.value === "O" && item.target.id === "8"){
      O8 = true
      console.log("foi 08")
    } else if(item.target.value === "O" && item.target.id === "9"){
      O9 = true
      console.log("foi 09")
    }  

    if( (X1 && X2 && X3) || (X4 && X5 && X6) || (X7 && X8 && X9) || (X1 && X4 && X7) || (X2 && X5 && X8) || (X3 && X6 && X9) || (X1 && X5 && X9) || (X3 && X5 && X7) ){
      XWin = true
    }
    if( (O1 && O2 && O3) || (O4 && O5 && O6) || (O7 && O8 && O9) || (O1 && O4 && O7) || (O2 && O5 && O8) || (O3 && O6 && O9) || (O1 && O5 && O9) || (O3 && O5 && O7)){
      OWin = true
    }
  }
  
  return (
    <S.Button value={player}
      id={buttonId}
      className={Mochiy.className}
      disabled={player === "O" || player === "X" ? true : false}
      onClick={(item) => { 
        HandlePlayer() 
        setTimeout(()=>{
          FuncaoTeste(item)
        },500)}}
      $iscoloro={colorO}
      $iscolorx={colorX}>

      {player}

    </S.Button>
  )
}